USE WAREHOUSE COMPUTE_WH;
CREATE DATABASE IF NOT EXISTS LEARN_DB;
USE DATABASE LEARN_DB;

CREATE SCHEMA IF NOT EXISTS RAW_STAGE; -- FOR KEEPING FILES IN SNOWFLAKE
CREATE SCHEMA IF NOT EXISTS RAW_SRC; -- KEEP SOURCE TABLES - MEDELLIAN ARCHITECTURES OR ANY OTHER PROCESS

CREATE SCHEMA IF NOT EXISTS STG; -- KEEP INTERMEDIATE TABLES OR SILVER TABLES
CREATE SCHEMA IF NOT EXISTS PRD; -- KEEP FINAL TABLES/GOLD TABLES

CREATE SCHEMA IF NOT EXISTS CONTROL; --FOR KEEPING TASKS, FILE FORMAT

