USE DATABASE LEARN_DB;
USE SCHEMA RAW_SRC;

INSERT INTO TPCH_SF10_NATION
    SELECT *
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.NATION
    LIMIT 100;


INSERT INTO TPCH_SF10_CUSTOMER
    SELECT *
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.CUSTOMER
    LIMIT 100;

INSERT INTO TPCH_SF10_ORDER
    SELECT *
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.ORDERS
    LIMIT 100;