USE DATABASE LEARN_DB;
use schema RAW_SRC;

--creating empty tables
CREATE OR REPLACE TABLE TPCH_SF10_CUSTOMER AS
    SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.CUSTOMER where 1=2 ;

CREATE OR REPLACE TABLE TPCH_SF10_ORDER AS
    SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.ORDERS where 1=2 ;

CREATE OR REPLACE TABLE RAW_SRC.TPCH_SF10_NATION AS
    SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.NATION where 1=2 ;

