USE DATABASE LEARN_DB;
USE SCHEMA RAW_SRC;

CREATE OR REPLACE STREAM SF10_CUSTOMER_STREAM ON TABLE TPCH_SF10_CUSTOMER;
CREATE OR REPLACE STREAM SF10_ORDER_STREAM ON TABLE TPCH_SF10_ORDER;
CREATE OR REPLACE STREAM SF10_CUSTOMER_NATION ON TABLE TPCH_SF10_NATION;

USE SCHEMA STG;

CREATE OR REPLACE STREAM CUSTOMER_ORDERS_STREAM ON TABLE CUSTOMER_ORDERS;