
USE DATABASE LEARN_DB;
USE SCHEMA RAW_SRC;
--EMPTY TABLES
DROP TABLE IF EXISTS STG.CUSTOMER_ORDERS;
DROP TABLE IF EXISTS LEARN_DB.PRD.CUSTOMER_ORDERS;

CREATE TABLE STG.CUSTOMER_ORDERS AS
    SELECT
        C.C_CUSTKEY AS CUSTOMERID,
        C.C_NAME AS CUSTOMERNAME,
        O.O_ORDERSTATUS AS ORDERSTATUS,
        O.O_TOTALPRICE AS TOTALPRICE,
        N.N_NAME AS NATIONNAME,
        ''::VARCHAR(20) AS ROW_STATUS,
        CURRENT_TIMESTAMP AS OP_DATE
    FROM TPCH_SF10_CUSTOMER C
    JOIN TPCH_SF10_ORDER O ON C.C_CUSTKEY = O.O_CUSTKEY
    JOIN TPCH_SF10_NATION N ON C.C_NATIONKEY = N.N_NATIONKEY
    WHERE 1=2;

CREATE TABLE LEARN_DB.PRD.CUSTOMER_ORDERS AS
     SELECT * FROM STG.CUSTOMER_ORDERS
    WHERE 1=2;
