COPY INTO RAW.CUSTOMERS
FROM @RAW.OLIST_INTERNAL_STAGE/olist_customers_dataset.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO RAW.ORDERS
FROM @RAW.OLIST_INTERNAL_STAGE/olist_orders_dataset.csv
FILE_FORMAT = CSV_FORMAT;