USE DATABASE learn_db;
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE=CSV
SKIP_HEADER=1
FIELD_OPTIONALLY_ENCLOSED_BY='"';

CREATE OR REPLACE STAGE OLIST_INTERNAL_STAGE
FILE_FORMAT = CSV_FORMAT;